<AdminScreen>

    Image:
        id: background
        source: 'images/cpto3.jpg'
        size_hint: None, None
        width: root.width
        height: root.height
        allow_stretch: True
        keep_ratio: False

    GridLayout:
        id: main_screen_layout
        cols: 3
        rows: 3
        size_hint: None, None
        width: root.width
        height: root.height

        Widget:
            id: blank_widget_1
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1

        MDLabel:
            id: appname_label
            text: "Administrátorský přístup"
            font_size: int(root.height * 0.05)
            multiline: False
            size_hint: None, None
            theme_text_color: "Custom"
            text_color: "#d20019"
            bold: True
            width: root.width * 0.8
            height: root.height * 0.1
            halign: "center"

        Widget:
            id: blank_widget_2
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1

        Widget:
            id: blank_widget_3
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.8

        MDCard:
            id: bgcard
            size_hint: None, None
            elevation: 1
            md_bg_color: "#ededed"
            style: "elevated"
            color: 0, 0, 0, 0
            #radius: [30, 30, 30, 30]
            width: root.width * 0.8
            height: root.height * 0.8

            GridLayout:
                id: login_inside_layout
                cols: 2
                rows: 4
                size_hint: 1, 1
                width: bgcard.width
                height: bgcard.height
                padding: 5, 5, 5, 5
                spacing: 5

                MDRectangleFlatButton:
                    id: admin_func_1
                    text: "Autorizace"
                    disabled: False
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    on_release: root.admin_func_1()
                
                MDRectangleFlatButton:
                    id: admin_func_2
                    text: "Přehled místností"
                    disabled: True
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    on_release: root.admin_func_2()

                MDRectangleFlatButton:
                    id: admin_func_3
                    text: "Autorizovat novou osobu"
                    disabled: False
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    on_release: root.admin_func_3()
                
                MDRectangleFlatButton:
                    id: admin_func_4
                    text: "Přidat novou místnost"
                    disabled: True
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    #on_release: 

                MDRectangleFlatButton:
                    id: admin_func_5
                    text: "Přehled uživatelů"
                    disabled: True
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    #on_release: 
                
                MDRectangleFlatButton:
                    id: admin_func_6
                    text: "Přidat nového uživatele"
                    disabled: True
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    #on_release: 

                MDRectangleFlatButton:
                    id: admin_func_7
                    text: "Budoucí funkce"
                    disabled: True
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    #on_release: 
                
                MDRectangleFlatButton:
                    id: admin_func_8
                    text: "Budoucí funkce"
                    disabled: True
                    text_color: "#FFFFFF"
                    md_bg_color: "#d20019"
                    line_color: "#d20019"
                    size_hint: 1, 1
                    width: bgcard.width * 0.4
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.2 * 0.3
                    #on_release: 

        Widget:
            id: blank_widget_4
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.8

        GridLayout:
            rows: 1
            cols: 1
            width: root.width * 0.1
            height: root.height * 0.1
            padding: root.width * 0.025, root.height * 0.025, root.width * 0.025, root.height * 0.025

            MDRectangleFlatButton:
                id: storno_button
                text: "<<<"
                text_color: "#FFFFFF"
                md_bg_color: "#d20019"
                line_color: "#d20019"
                on_release: app.StornoButton()
                size_hint: 1, 1
                width: root.width * 0.05
                height: root.height * 0.05
                font_size: root.height * 0.025

        MDLabel:
            id: clock
            text: "??:??"
            font_size: int(root.height * 0.05)
            size_hint: None, None
            theme_text_color: "Custom"
            text_color: "#d20019"
            bold: True
            width: root.width * 0.8
            height: root.height * 0.1
            halign: "right"

        Widget:
            id: blank_widget_5
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1