<LoginScreen>:

    Image:
        id: background
        source: 'images/cpto3.jpg'
        size_hint: None, None
        width: root.width
        height: root.height
        allow_stretch: True
        keep_ratio: False

    GridLayout:
        id: main_screen_layout
        cols: 3
        rows: 3
        size_hint: None, None
        width: root.width
        height: root.height

        Widget:
            id: blank_widget_1
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1

        MDLabel:
            id: appname_label
            text: "Aplikace pro správu klíčů CPTO"
            font_size: int(root.height * 0.05)
            multiline: False
            size_hint: None, None
            theme_text_color: "Custom"
            text_color: 0.0, .35, .39, 1
            bold: True
            width: root.width * 0.8
            height: root.height * 0.1
            halign: "center"

        Widget:
            id: blank_widget_2
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1

        Widget:
            id: blank_widget_3
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.8

        MDCard:
            id: bgcard
            size_hint: None, None
            elevation: 1
            md_bg_color: "#ededed"
            style: "elevated"
            color: 0, 0, 0, 0
            #radius: [30, 30, 30, 30]
            width: root.width * 0.8
            height: root.height * 0.8

            GridLayout:
                id: login_inside_layout
                cols: 1
                rows: 3
                size_hint: None, None
                width: bgcard.width
                height: bgcard.height
                padding: bgcard.width * 0.1, bgcard.height * 0.1, bgcard.width * 0.1, bgcard.height * 0.1
                spacing: bgcard.height * 0.1

                MDTextField:
                    id: user
                    mode: "rectangle"
                    text_color_normal: "#005963"
                    text_color_focus: "#000000"
                    hint_text_color_normal: "#005963"
                    hint_text_color_focus: "#000000"
                    background_color: "#FFFFFF"
                    multiline: False
                    fill_color_focus: "#FFFFFF"
                    line_color_normal: "#005963"
                    line_color_focus: "#000000"
                    hint_text: "Přihlašovací jméno"
                    icon_right: "account"
                    icon_right_color_focus: "#000000"
                    icon_right_color_normal: "#005963"
                    size_hint: None, None
                    width: bgcard.width * 0.8
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.1

                MDTextField:
                    id: password
                    mode: "rectangle"
                    text_color_normal: "#005963"
                    text_color_focus: "#000000"
                    hint_text_color_normal: "#005963"
                    hint_text_color_focus: "#000000"
                    background_color: "#FFFFFF"
                    multiline: False
                    fill_color_focus: "#FFFFFF"
                    line_color_normal: "#005963"
                    line_color_focus: "#000000"
                    hint_text: "Heslo"
                    icon_right: "key-variant"
                    icon_right_color_focus: "#000000"
                    icon_right_color_normal: "#005963"
                    password: True
                    size_hint: None, None
                    width: bgcard.width * 0.8
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.1


                MDRectangleFlatButton:
                    id: login_button
                    text: "Přihlásit se"
                    text_color: "#FFFFFF"
                    md_bg_color: "#005963"
                    line_color: "#005963"
                    on_release: root.PrihasitSeButtonFunction()
                    size_hint: 1, None
                    width: bgcard.width * 0.8
                    height: bgcard.height * 0.2
                    font_size: bgcard.height * 0.15
        
        Widget:
            id: blank_widget_4
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.8

        Widget:
            id: blank_widget_5
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1

        MDLabel:
            id: clock
            text: "??:??"
            font_size: int(root.height * 0.05)
            size_hint: None, None
            theme_text_color: "Custom"
            text_color: 0.0, .35, .39, 1
            bold: True
            width: root.width * 0.8
            height: root.height * 0.1
            halign: "right"

        Widget:
            id: blank_widget_5
            size_hint: None, None
            color: 0, 0, 0, 0
            width: root.width * 0.1
            height: root.height * 0.1