#:kivy 2.1.0
#:import kivy kivy


<LoginWindow>
    cols: 1
    rows: 3
    size_hint: (0.6, 0.7)
    pos_hint: {"center_x": 0.5, "center_y":0.5}
    top: root.height
    bottom: 0

    Label:
        text: 'Zadejte přihlašovací údaje:'
        color: 0, 0, 0, 1
        font_size: 48
        bold: True
        size_hint: (1, 0.75)

    GridLayout:
        cols: 2
        rows: 2
        #pos_hint: {'center' : 1}

        Label:
            text: 'Jméno: '
            color: 0, 0, 0, 1
            font_size: 32
            #pos_hint: {'right' : 1, 'top': 1}

        TextInput:
            size_hint: (1, 0.5)
            multiline: False
            #pos_hint: {'right' : 0, 'top': 1}

        Label:
            color: 0, 0, 0, 1
            font_size: 32
            text: 'Heslo: '
            #pos_hint: {'right' : 1, 'top': 0}

        TextInput:
            size_hint: (1, 0.5)
            #pos_hint: {'right' : 0, 'top': 0}
            # pridat moznost zakryti znaku
            multiline: False
    
    GridLayout:
        cols: 2
        rows: 1

        Button:
            #width: 100
            background_color: 1.0, 0.0, 0.0, 1.0
            text: 'STORNO'
            bold: True
            font_size: 32
            on_press: app.stop()    
            background_color: 1.0, 0.2, 0.2, 1
            #pos_hint: {'right': 0, 'top': 0}

        Button:
            #width: 100
            background_color: 1.0, 0.0, 0.0, 1.0
            text: 'Pokračovat'
            bold: True
            font_size: 32
            background_color: 0.2, 0.6, 0.2, 1
            size_hint: (1,0.5)
            #pos_hint: {'right': 1, 'top': 0}
