#:kivy 2.1.0
#:import kivy kivy
#:set tex_inp_red 20

# tmavsi prf : 0.0, .35, .39, 1    #005963
# seda       : .93, .93, .93, 1    #ededed
# prf        : 0.0, .45, .50, 1    #007380

<LoginWindow>
    cols: 1
    rows: 1
    size_hint: (1, 1)
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'cpto2.jpg'

    GridLayout:
        cols: 1
        rows: 3
        size_hint: (0.6, 0.7)
        padding: (150, 150)
        pos_hint: {"center_x": 0.5, "center_y":0.5}
        top: root.height
        bottom: 0

        MDLabel:
            text: 'Zadejte přihlašovací údaje:'
            text_color: 0, 0, 0, 1
            font_size: 48
            font_style: 'H4'
            bold: True
            size_hint: (1, 0.75)
            halign: 'center'
            theme_text_color: 'Custom'

        GridLayout:
            cols: 1
            rows: 2
            #pos_hint: {'center' : 1}

            MDTextField:
                size_hint: (1, .4)
                multiline: False
                hint_text: 'Přihlašovací jméno'
                current_hint_text_color: 0, 0, 0, 1
                size_hint_x: .8
                helper_text_mode: "on_focus"
                mode: "round"
                pos_hint: {'center_x' : .5, 'center_y' : .5}
                font_size: self.height - tex_inp_red

            MDTextField:
                size_hint: (1, .4)
                multiline: False
                hint_text: 'Heslo'
                current_hint_text_color: 0, 0, 0, 1
                size_hint_x: .8
                helper_text_mode: "on_focus"
                mode: "round"
                pos_hint: {'center_x' : .5, 'center_y' : .5}
                font_size: self.height - tex_inp_red
                password: True
        
        GridLayout:
            cols: 2
            rows: 1

            Button:
                #width: 100
                background_color: 1.0, 0.0, 0.0, 1.0
                text: 'Pokračovat'
                bold: True
                font_size: 32
                background_color: 0.2, 0.6, 0.2, 1
                size_hint: (.5,.5)
                #padding: 100
                #pos_hint: {'right': 1, 'top': 0}
