#:kivy 2.1.0
#:import kivy kivy

# tmavsi prf : 0.0, .35, .39, 1    #005963
# seda       : .93, .93, .93, 1    #ededed
# prf        : 0.0, .45, .50, 1    #007380

<SearchResultWidget>
    height: 40
    size_hint: 1, 0.06
    
    MDLabel:
        id: searchresultwidget_label_content
        size_hint: 1, 1
        text: ""


<LoginScreen>:  

    Image:
        source: 'cpto2.jpg'

    MDLabel:
        id: appname_label
        text: "Aplikace pro správu klíčů CPTO"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.95}
        bold: True

    MDCard:
        size_hint: None, None
        size: 300, 300
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: user
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#FFFFFF"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Přihlašovací jméno"
            icon_right: "account"
            icon_right_color_focus: "#000000"
            icon_right_color_normal: "#005963"
            size_hint_x: None
            width: 200
            font_size: 18
            pos_hint: {"center_x": 0.5}

        MDTextField:
            id: password
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#FFFFFF"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Heslo"
            icon_right: "key-variant"
            icon_right_color_focus: "#000000"
            icon_right_color_normal: "#005963"
            size_hint_x: None
            width: 200
            font_size: 18
            pos_hint: {"center_x": 0.5}
            password: True

        MDRoundFlatButton:
            text: "Přihlásit se"
            text_color: "#FFFFFF"
            md_bg_color: "#005963"
            font_size: 24
            pos_hint: {'right': 1}
            on_release: root.PrihasitSeButtonFunction() 

<KeySelectionScreen>

    Image:
        source: 'cpto2.jpg'

    MDLabel:
        id: appname_label2
        text: "Aplikace pro správu klíčů CPTO"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.95}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: keysearch
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#005963"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Učebna nebo název klíče"
            size_hint: 1, 0.1
            font_size: 18
            pos_hint: {"center_x": .5, "y": 1.0}
            on_text: root.SearchKeyTextInputFunction()

        BoxLayout:
            size_hint: 1, 0.9
            id: key_widget_scrollview
            pos_hint: {"x": 0.0}

#        MDDataTable:
#            size_hint: 0.9, 0.6
#            pos_hint: {"center_x": 0.5, "center_y": 0.5}
#            column_data: [('Template Id', dp(30)), ('Name', dp(30))]
#            row_data: [('23lkjk33', 'Ayang Paul'), ('28ij399kk', 'Ringwa Justin')]