#:kivy 2.1.0
#:import kivy kivy

# tmavsi prf : 0.0, .35, .39, 1    #005963
# seda       : .93, .93, .93, 1    #ededed
# prf        : 0.0, .45, .50, 1    #007381

# origo prf : 

<SearchResultWidget>
    size_hint: 1, 0.06

    MDRoundFlatButton:
        id: searchresultwidget_label_content
        size_hint: 1, 1
        text: "ERROR"
        pos_hint: {"center_x": .5, "y": 1.0}
        on_release: app.SearchResultWidgetClickFunction(self.parent)
        text_color: "#FFFFFF"
        md_bg_color: "#005963"
        line_color: "#005963"
        icon_color: "#FFFFFF"


<LoginScreen>:

    Image:
        id: background
        source: 'cpto3.jpg'
        size_hint: None, None
        allow_stretch: True
        keep_ratio: False

    MDLabel:
        id: appname_label
        text: "Aplikace pro správu klíčů CPTO"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 600, 600
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        orientation: 'vertical'
        md_bg_color: "#ededed"
        style: "elevated"
        radius: [30, 30, 30, 30]

        GridLayout:
            id: login_inside_layout
            cols: 3
            rows: 7
            size_hint: None, 1.0

            # vrchni odszeni
            # leve odsazeni
            Widget:
                size_hint: None, None
                height: 50
                width: 75
            
            # vrchni odsazeni
            Widget:
                size_hint: None, None
                height: 50

            # vrchni odsazeni
            # prave odsazeni
            Widget:
                size_hint: None, None
                height: 50
                width: 75

            # leve odsazeni
            Widget:
                size_hint: None, None
                width: 75

            MDTextField:
                id: user
                mode: "round"
                text_color_normal: "#005963"
                text_color_focus: "#000000"
                background_color: "#FFFFFF"
                multiline: False
                fill_color_focus: "#FFFFFF"
                line_color_normal: "#005963"
                line_color_focus: "#000000"
                hint_text: "Přihlašovací jméno"
                icon_right: "account"
                icon_right_color_focus: "#000000"
                icon_right_color_normal: "#005963"
                font_size: root.height // 12
                pos_hint: {"center_x": 0.5}

            # prave odsazeni
            Widget:
                size_hint: None, None
                width: 75

            # prostredni odsazeni
            # leve odsazeni
            Widget:
                size_hint: None, None
                width: 75
                height: 50

            # prostredni odsazeni
            Widget:
                size_hint: None, None
                height: 50

            # prostredni odsazeni
            # prave odsazeni
            Widget:
                size_hint: None, None
                width: 75
                height: 50

            # leve odsazeni
            Widget:
                size_hint: None, None
                width: 75

            MDTextField:
                id: password
                mode: "round"
                text_color_normal: "#005963"
                text_color_focus: "#000000"
                background_color: "#FFFFFF"
                multiline: False
                fill_color_focus: "#FFFFFF"
                line_color_normal: "#005963"
                line_color_focus: "#000000"
                hint_text: "Heslo"
                icon_right: "key-variant"
                icon_right_color_focus: "#000000"
                icon_right_color_normal: "#005963"
                font_size: root.height // 12
                pos_hint: {"center_x": 0.5}
                password: True

            # prave odsazeni
            Widget:
                size_hint: None, None
                width: 75

            # prostredni odsazeni
            # leve odsazeni
            Widget:
                size_hint: None, None
                width: 75
                height: 50

            # prostredni odsazeni
            Widget:
                size_hint: None, None
                height: 50

            # prostredni odsazeni
            # prave odsazeni
            Widget:
                size_hint: None, None
                width: 75
                height: 50

            # leve odsazeni
            Widget:
                size_hint: None, None
                width: 75
                height: 50

            GridLayout:
                cols: 2
                rows: 1

                Widget:
                    size_hint_x: None
                    width: password.width // 2

                MDRoundFlatButton:
                    text: "Přihlásit se"
                    text_color: "#FFFFFF"
                    md_bg_color: "#005963"
                    font_size: root.height // 12
                    pos_hint: {'center_x': 0.75}
                    on_release: root.PrihasitSeButtonFunction()

            # prave odsazeni
            Widget:
                size_hint: None, None
                width: 75

            # dolni odszeni
            # leve odsazeni
            Widget:
                size_hint: None, None
                height: 50
                width: 75
            
            # dolni odsazeni
            Widget:
                size_hint: None, None
                height: 50

            # dolni odsazeni
            # prave odsazeni
            Widget:
                size_hint: None, None
                height: 50
                width: 75

    #MDLabel:
    #    id: time_label


<ActionSelectionScreen>:

    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label
        text: "Aplikace pro správu klíčů CPTO"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 300, 300
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        GridLayout:
            rows: 2
            cols: 1
            size_hint: 1, 1
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            spacing: 25

            MDRoundFlatButton:
                text: "PŮJČIT"
                text_color: "#FFFFFF"
                md_bg_color: "#005963"
                font_size: 32
                line_color: "#005963"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                size_hint: 1, 1
                on_release: root.pujcit() 

            MDRoundFlatButton:
                text: "VRÁTIT"
                text_color: "#FFFFFF"
                md_bg_color: "#005963"
                font_size: 32
                line_color: "#005963"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                size_hint: 1, 1
                on_release: root.vratit() 


<BorrowingSelectionScreen>:

    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label
        text: "Zvolte výpůjčku k ukončení"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: borrowingsearch
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#005963"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Poschodí"
            size_hint: 1, 0.1
            font_size: 18
            padding: 25
            pos_hint: {"center_x": .5, "y": 1.0}
            on_text: root.SearchBorrowingTextInputFunction()

        GridLayout:
            size_hint: 1, 0.9
            padding: 25
            id: borrowings_widget_scrollview
            pos_hint: {"x": 0.0}
            cols: 1
            rows: 9
            spacing: 5
            row_default_height: 40


<FloorSelectionScreen>:

    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label
        text: "Zvolte podlaží"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: floorsearch
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#005963"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Poschodí"
            size_hint: 1, 0.1
            font_size: 18
            padding: 25
            pos_hint: {"center_x": .5, "y": 1.0}
            on_text: root.SearchFloorTextInputFunction()

        GridLayout:
            size_hint: 1, 0.9
            padding: 25
            id: floor_widget_scrollview
            pos_hint: {"x": 0.0}
            cols: 1
            rows: 9
            spacing: 5
            row_default_height: 40


<RoomSelectionScreen>

    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label
        text: "Vyberte místnost"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: roomsearch
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#005963"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Učebna"
            size_hint: 1, 0.1
            font_size: 18
            padding: 25
            pos_hint: {"center_x": .5, "y": 1.0}
            on_text: root.SearchRoomTextInputFunction()

        GridLayout:
            size_hint: 1, 0.9
            padding: 25
            id: room_widget_scrollview
            pos_hint: {"x": 0.0}
            cols: 1
            rows: 9
            spacing: 5
            row_default_height: 40


<KeySelectionScreen>

    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label
        text: "Vyberte klíč"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: keysearch
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#005963"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Registrační číslo klíče"
            size_hint: 1, 0.1
            font_size: 18
            padding: 25
            pos_hint: {"center_x": .5, "y": 1.0}
            on_text: root.SearchKeyTextInputFunction()

        GridLayout:
            size_hint: 1, 0.9
            padding: 25
            id: key_widget_scrollview
            pos_hint: {"x": 0.0}
            cols: 1
            rows: 9
            spacing: 5
            row_default_height: 40


<PersonSelectionScreen>
    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label3
        text: "Kdo si klíč půjčuje?"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        MDTextField:
            id: personsearch
            mode: "round"
            text_color_normal: "#005963"
            text_color_focus: "#000000"
            background_color: "#005963"
            multiline: False
            fill_color_focus: "#FFFFFF"
            line_color_normal: "#005963"
            line_color_focus: "#000000"
            hint_text: "Jméno hledané osoby"
            size_hint: 1, 0.1
            font_size: 18
            padding: 25
            pos_hint: {"center_x": .5, "y": 1.0}
            on_text: root.PersonSearchTextInputFunction()

        GridLayout:
            size_hint: 1, 0.9
            padding: 25
            id: person_widget_scrollview
            pos_hint: {"x": 0.0}
            cols: 1
            rows: 9
            spacing: 5
            row_default_height: 40


<TimeSelectionScreen>
    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label4
        text: "Aplikace pro správu klíčů CPTO"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        GridLayout:
            id: timeselection_gridlayout
            cols: 1
            rows: 4
            size_hint: 1, 1
            pos_hint: {"center_x": 0.5, "y": 1.0}
            spacing: 25
            padding: 25

            MDLabel:
                id: timeselection_topiclabel
                text: "Do kdy chcete klíč vypůjčit?"
                theme_text_color: "Custom"
                text_color: 0.0, .35, .39, 1
                font_size: 32
                size_hint: 1, 0.4
                halign: "center"
                valign: "top"
                pos_hint: {"top": 1.0}
                bold: True
                multiline: False
            
            # vyber a zobrazeni data
            GridLayout:
                id: datepicker_layout
                cols: 2
                rows: 1
                size_hint: 1, 0.2
                pos_hint: {"center_x": 0.5}
                spacing: 50

                MDRoundFlatButton:
                    id: datepicker_button
                    text: "Vybrat datum"
                    text_color: "#FFFFFF"
                    md_bg_color: "#005963"
                    line_color: "#005963"
                    font_size: 24
                    size_hint: 0.5, 0.5
                    on_release: app.show_date_picker()

                MDLabel:
                    id: datepicker_label
                    text: "Nebylo vybráno žádné datum"
                    font_size: 24
                    theme_text_color: "Custom"
                    text_color: 0.0, .35, .39, 1
                    size_hint: 0.5, 0.5
                    valign: "bottom"

            # vyber a zobrazeni casu
            GridLayout:
                id: timepicker_layout
                cols: 2
                rows: 1
                size_hint: 1, 0.2
                pos_hint: {"center_x": 0.5}
                spacing: 50

                MDRoundFlatButton:
                    id: timepicker_button
                    text: "Vybrat čas"
                    text_color: "#FFFFFF"
                    md_bg_color: "#005963"
                    line_color: "#005963"
                    font_size: 24
                    size_hint: 0.5, 0.5
                    on_release: app.show_time_picker()

                MDLabel:
                    id: timepicker_label
                    text: "Nebyl vybrán žádný čas"
                    font_size: 24
                    theme_text_color: "Custom"
                    text_color: 0.0, .35, .39, 1
                    size_hint: 0.5, 0.5
                    valign: "bottom"

            MDRoundFlatButton:
                id: timeselection_confirmbutton
                text: "Potvrdit čas"
                text_color: "#FFFFFF"
                md_bg_color: "#005963"
                line_color: "#005963"
                font_size: 24
                size_hint: 1, 0.5
                pos_hint: {"center_X": 0.75}
                on_release: root.confirm_timestamps()


<ReviewScreen>
    Image:
        source: 'cpto3.jpg'

    MDLabel:
        id: appname_label4
        text: "Rekapitulace"
        font_size: 40
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 15
        theme_text_color: "Custom"
        text_color: 0.0, .35, .39, 1
        pos_hint: {'top': 0.98}
        bold: True

    MDCard:
        size_hint: None, None
        size: 900, 500
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        elevation: 1
        padding: 25
        spacing: 25
        orientation: 'vertical'
        md_bg_color: "#ededed"

        GridLayout:
            id: review_layout
            cols: 1
            rows: 5
            size_hint: 1, 1
            row_default_height: 100
            row_force_default: True
            #spacing: 30

            # MDLabel:
            #     id: rev_topiclabel
            #     text: "Rekapitulace"
            #     theme_text_color: "Custom"
            #     text_color: 0.0, .35, .39, 1
            #     font_size: 32
            #     size_hint: 1, 0.4
            #     halign: "center"
            #     valign: "top"
            #     pos_hint: {"top": 1.0}
            #     bold: True
            #     multiline: False

            # kdo půjčuje klíč
            # MDLabel:
            #     id: rev_lab_lender
            #     text: "Oprávněná osoba: "
            #     font_size: 24
            #     theme_text_color: "Custom"
            #     text_color: 0.0, .35, .39, 1
            #     size_hint: 0.5, 0.5
            #     valign: "center"

            # komu ho půjčuje
            MDLabel:
                id: rev_lab_borrower
                text: "Komu půjčuje: "
                font_size: 32
                theme_text_color: "Custom"
                text_color: 0.0, .35, .39, 1
                size_hint: 0.5, 0.5
                valign: "center"
                
            # jaký klíč půjčuje
            MDLabel:
                id: rev_lab_key
                text: "Klíč: "
                font_size: 32
                theme_text_color: "Custom"
                text_color: 0.0, .35, .39, 1
                size_hint: 0.5, 0.5
                valign: "center"

            # kvůli které místnosti
            MDLabel:
                id: rev_lab_room
                text: "Místnost: "
                font_size: 32
                theme_text_color: "Custom"
                text_color: 0.0, .35, .39, 1
                size_hint: 0.5, 0.5
                valign: "center"

            # na jak dlouho jej půjčuje
            MDLabel:
                id: rev_lab_starttime
                text: "Kdy: "
                font_size: 32
                theme_text_color: "Custom"
                text_color: 0.0, .35, .39, 1
                size_hint: 0.5, 0.5
                valign: "center"

            # MDLabel:
            #     id: rev_lab_endtime
            #     text: "Do: "
            #     font_size: 24
            #     theme_text_color: "Custom"
            #     text_color: 0.0, .35, .39, 1
            #     size_hint: 0.5, 0.5
            #     valign: "center"

            # tlačítka
            GridLayout:
                rows: 1
                cols: 2
                size_hint: 1, 1
                row_default_height: 50
                row_force_default: True
                spacing: 50

                MDRoundFlatButton:
                    id: timeselection_confirmbutton
                    text: "Aktualizovat"
                    text_color: "#FFFFFF"
                    md_bg_color: "#005963"
                    line_color: "#005963"
                    font_size: 24
                    size_hint: 0.5, 0.5
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    on_release: app.update_review_information()

                MDRoundFlatButton:
                    id: timeselection_confirmbutton
                    text: "Dokončit"
                    text_color: "#FFFFFF"
                    md_bg_color: "#005963"
                    line_color: "#005963"
                    font_size: 24
                    size_hint: 0.5, 0.5
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    on_release: app.complete_borrowing_session()